apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260513-140214-8yye6fw8pwz1-service
spec:
  selector:
    app: enterprise-system-20260513-140214-8yye6fw8pwz1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
